alien_items = [
        {"name": "Xenon Crystal", "value": 50},
        {"name": "Plasma Blaster", "value": 75},
        {"name": "Fuel can", "value": 0},
        {"name": "Quantum Probe", "value": 60},
        {"name": "Neutron Shield", "value": 70},
        {"name": "Alien Alloy", "value": 40},
        {"name": "Teleportation Device", "value": 90},
        {"name": "Laser Sword", "value": 65},
        {"name": "Anti-Gravity Boots", "value": 80},
        {"name": "Mind Control Helm", "value": 55},
        {"name": "Fuel can", "value": 0},
        {"name": "Mega-Blaster Cannon", "value": 100},
        {"name": "Astro-Communicator", "value": 45},
        {"name": "Energy Harvester", "value": 85},
        {"name": "Hyperdrive Engine", "value": 95},
        {"name": "Cosmic Elixir", "value": 30},
        {"name": "Nano-Disruptor", "value": 70},
        {"name": "Starship Blueprint", "value": 60},
        {"name": "Fuel can", "value": 0},
        {"name": "Repair kit", "value": 0},
        {"name": "Invisibility Cloak", "value": 80},
        {"name": "Alien Artifact", "value": 50},
        {"name": "Time-Warp Generator", "value": 90},
        {"name": "Warp Core Stabilizer", "value": 75},
        {"name": "Xenon Crystal", "value": 50},
        {"name": "Plasma Blaster", "value": 75},
        {"name": "Quantum Probe", "value": 60},
        {"name": "Neutron Shield", "value": 70},
        {"name": "Alien Alloy", "value": 40},
        {"name": "Fuel can", "value": 0},
        {"name": "Repair kit", "value": 0},
        {"name": "Teleportation Device", "value": 90},
        {"name": "Laser Sword", "value": 65},
        {"name": "Anti-Gravity Boots", "value": 80},
        {"name": "Repair kit", "value": 0},
        {"name": "Mind Control Helm", "value": 55},
        {"name": "Fuel can", "value": 0},
        {"name": "Mega-Blaster Cannon", "value": 100},
        {"name": "Astro-Communicator", "value": 45},
        {"name": "Energy Harvester", "value": 85},
        {"name": "Hyperdrive Engine", "value": 95},
        {"name": "Cosmic Elixir", "value": 30},
        {"name": "Nano-Disruptor", "value": 70},
        {"name": "Fuel can", "value": 0},
        {"name": "Repair kit", "value": 0},
        {"name": "Fuel can", "value": 0},
        {"name": "Starship Blueprint", "value": 60},
        {"name": "Invisibility Cloak", "value": 80},
        {"name": "Alien Artifact", "value": 50},
        {"name": "Time-Warp Generator", "value": 90},
        {"name": "Warp Core Stabilizer", "value": 75},
        {"name": "Plasma Gauntlets", "value": 70},
        {"name": "Quantum Resonator", "value": 85},
        {"name": "Stellar Compass", "value": 65},
        {"name": "Celestial Harmonizer", "value": 80},
        {"name": "Galactic Map", "value": 55},
        {"name": "Cosmic Data Crystal", "value": 75},
        {"name": "Fuel can", "value": 0},
        {"name": "Fuel can", "value": 0},
        {"name": "Neutrino Scanners", "value": 90},
        {"name": "Repair kit", "value": 0},
        {"name": "Astro-Navigation Chart", "value": 70},
        {"name": "Fuel can", "value": 0},
        {"name": "Lunar Medallion", "value": 45},
        {"name": "Fuel can", "value": 0},
        {"name": "Space-time Capacitor", "value": 60},
        {"name": "Plasma Blade", "value": 70},
        {"name": "Quantum Core", "value": 85},
        {"name": "Stellar Ring", "value": 65},
        {"name": "Celestial Crystal", "value": 80},
        {"name": "Fuel can", "value": 0},
        {"name": "Galactic Handbook", "value": 55},
        {"name": "Cosmic Beacon", "value": 75},
        {"name": "Neutron Capacitor", "value": 90},
        {"name": "Astro-Scanner", "value": 70},
        {"name": "Repair kit", "value": 0},
        {"name": "Fuel can", "value": 0},
        {"name": "Lunar Amulet", "value": 45},
        {"name": "Fuel can", "value": 0},
        {"name": "Temporal Disruptor", "value": 60},
        {"name": "Plasma Pulse Rifle", "value": 75},
        {"name": "Nebula Crystal Shard", "value": 65},
        {"name": "Quantum Entanglement Device", "value": 90},
        {"name": "Celestial Star Chart", "value": 70},
        {"name": "Galactic Energy Source", "value": 85},
        {"name": "Fuel can", "value": 0},
        {"name": "Repair kit", "value": 0},
        {"name": "Interstellar Relic", "value": 50},
        {"name": "Fuel can", "value": 0},
        {"name": "Astral Beacon", "value": 75},
        {"name": "Dimensional Key", "value": 80},
        {"name": "Cosmic Elemental Core", "value": 95},
        {"name": "Fuel can", "value": 0},
        {"name": "Aetherial Harmonizer", "value": 55},
        {"name": "Solar Flare Staff", "value": 70},
        {"name": "Plasma-infused Crystals", "value": 80},
        {"name": "Repair kit", "value": 0},
        {"name": "Void Anchor", "value": 90},
        {"name": "Fuel can", "value": 0},
        {"name": "Nebula Explorer's Suit", "value": 75},
        {"name": "Starship Repair Drone", "value": 65},
        {"name": "Astro-Graviton Device", "value": 60},
        {"name": "Repair kit", "value": 0},
        {"name": "Quantum Wave Amplifier", "value": 85},
        {"name": "Interstellar Compass", "value": 70},
        {"name": "Celestial Amulet", "value": 45},
        {"name": "Exoplanetary Data Cube", "value": 55},
        {"name": "Fuel can", "value": 0},
    ]